spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee
    username: root
    password: '0210'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
